linters-settings:
  custom:
    nxgoenforcemoduleboundaries:
      path: nxgoenforcemoduleboundaries.so
      description: The description of the linter
      original-url: github.com/golangci/example-linter

linters:
  enable:
    - nxgoenforcemoduleboundaries
